### ISSUE TITLE
Integrate with Pageviews

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1001]
Sometimes users want to show pageview count per-entry. There's a cool plugin by some awesome developer that should make this nominal: https://github.com/pressjitsu/pageviews

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995547266665243)

**Comment by soulseekah** [comment]
I've added the `[gv_pageviews]` shortcode for this (we can add is as a standalone field but for now I'd like it to be added into Custom Content to hide the limitations below, but it can be used outside of a View altogether by supplying the `id` attribute).

The limitations:

- Cannot sort, order, filter by pageview, since they're all fetched via AJAX calls. Pageviews was never really meant for this but it can still be done with a bit of tinkering and server-side HTTP calls (slow!)
- The shortcode cannot be used outside of the Content field without supplying the `id`.
- Numbers are only incremented on Single Entry views. Just displayed anywhere else. This is a limitation in PageViews that does only 1 specific increment per page (thus a pageview).

The shortcode:

`[gv_pageviews]` has these attributes:

- ` preload`. The preload text, default is `...`
- `id`. An entry ID override! Is `{entry_id}` by default.

The pageviews key is prefixed with `GV` for entries to avoid collisions with post IDs.

Needs testing, download the pageviews plugin from here: https://pageviews.io/

![edit](https://user-images.githubusercontent.com/685880/67159048-2ecea400-f348-11e9-9161-f538d3cfa64e.gif)

**Comment by zackkatz** [comment]
I'll take your word for it that this works.

@jlgrisham Can you write a doc for this, using phrases you think people would search for? Like "page counter", etc? Please make sure to include Gennady's limitations section

**Comment by zackkatz** [comment]
Doc here: https://docs.gravityview.co/article/683-track-pageviews-for-entries
