### ISSUE TITLE
Question: should we delete Post Images when they are replaced on Edit Entry page?

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1003]
One of our users asked:

>I've also noticed that if a user changes their mind and replaces the existing image with something different, it leaves the old image in the Media Library. Shouldn't it remove it? Otherwise you could end up with a whole lot of unattached and unnecessary images bloating the database and upload folders. Hope you can help.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/571194912/14324/

**Comment by zackkatz** [comment]
No, ​​I don't think deleting images when they are changed in an etry would be expected behavior for WordPress. For example, if you delete a post in WordPress, the images uploaded to that post aren't deleted. This behavior is something you could have developed; there are developer "hooks" that would allow for this.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1581335896/35957
