### ISSUE TITLE
Multiple Views on a page don't work

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1036]
Basically, when there are two Views on a page like this:

[gravityview id='2116']
[gravityview id='674']

...Debug bar shows:

Warnings
GravityView_Advanced_Filtering[filter_search_criteria] Empty View ID.
GravityView_Advanced_Filtering[filter_search_criteria] Empty View ID.

Tested with GV 2.0.4
Removing Adv Filters doesn't fix it.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/580594446/14631/

**Comment by zackkatz** [comment]
```
if ( class_exists( 'GravityView_View_Data' ) && GravityView_View_Data::getInstance()->has_multiple_views() ) {
	$args['gvid'] = gravityview_get_view_id();
}
```

@soulseekah GravityView_View_Data::getInstance()->has_multiple_views() doesn't work properly.

The size of the View_Collection goes down. At the beginning of the page load, there are TWO, then by the time it's generating entry links, there is only one View in the collection, **so `$args['gvid']` is never added** to the entry links.

![](http://share.gravityview.co/p6ekzG+)

**Comment by dm196501** [comment]
I'm having the same issue; however, I'm not a developer and need to know if this error is going to correct itself, or do I need to go in and add the script to php file?

**Comment by soulseekah** [comment]
A quick intermediate update.

So `gvid` is not needed for the entry links (although, after looking at the delete entry link code I just added it implicitly (see `get_delete_link`)). The whole functionality works without it (as well as with it), it even saves the entry. The only issue is that the red errors are shown.

![image](https://user-images.githubusercontent.com/685880/40086055-3687f0c6-58b6-11e8-810d-b6e3b58733cc.png)

![image](https://user-images.githubusercontent.com/685880/40086767-1debd624-58b9-11e8-9058-1a6ec81a5330.png)

In 1.x the top shortcode was not even checked.

The underlying issue is that both shortcodes are rendered in edit view in 2.x while only one is rendered in 1.x; even though an implicit `gvid` is added to the URLs.

**Comment by soulseekah** [comment]
The stacks:

1.x:

```
14	0.7711	94430264	do_shortcode_tag( )	.../shortcodes.php:197
15	0.7711	94430728	GravityView_Shortcode->shortcode( )	.../shortcodes.php:319
16	0.7717	94431712	GravityView_frontend->render_view( )	.../class-gravityview-shortcode.php:58
17	0.7736	94474408	do_action( )	.../class-frontend-views.php:977
18	0.7736	94474784	WP_Hook->do_action( )	.../plugin.php:453
19	0.7736	94474784	WP_Hook->apply_filters( )	.../class-wp-hook.php:310
20	0.7736	94475912	GravityView_Edit_Entry_Render->init( )	.../class-wp-hook.php:286
21	0.7749	94806448	GravityView_Edit_Entry_Render->user_can_edit_entry( )	.../class-edit-entry-render.php:235
```

2.x:
```
14	0.7635	95942760	do_shortcode_tag( )	.../shortcodes.php:197
15	0.7635	95943224	GV\Shortcodes\gravityview->callback( )	.../shortcodes.php:319
16	0.7714	95972304	GV\Edit_Entry_Renderer->render( )	.../class-gv-shortcode-gravityview.php:128
17	0.7725	95993984	do_action( )	.../class-gv-renderer-entry-edit.php:40
18	0.7725	95994360	WP_Hook->do_action( )	.../plugin.php:453
19	0.7725	95994360	WP_Hook->apply_filters( )	.../class-wp-hook.php:310
20	0.7725	95995488	GravityView_Edit_Entry_Render->init( )	.../class-wp-hook.php:286
21	0.7739	96260512	GravityView_Edit_Entry_Render->user_can_edit_entry( )	.../class-edit-entry-render.php:238
```

Some suppression on multiple views is not kicking in the 2.x callback I'm sure. Probably related to the legacy `GravityView_View_Data::getInstance()->has_multiple_views()` which is not being checked/set/etc.
