### ISSUE TITLE
The option "Hide View data until search is performed" no longer works

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1046]
**Updated:**

On GV 2.0.6.1

This option only works if you access the /view/ directly. If the View is embedded on a page, it doesn't work.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995551587210121)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/583803012/14743/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/584639776/14762/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/578464395/14537/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/586140345/14829

**Comment by zackkatz** [comment]
@rafaehlers can you please reproduce on .com.br when you have a chance?

**Comment by soulseekah** [comment]
On a related note: GP Populate Anything throws an error here:

![image](https://user-images.githubusercontent.com/685880/66139924-e904a280-e609-11e9-962c-e52d3d40025e.png)

Because we're sending a keyless search filter when the "Hide View data until search is performed" option is checked:

![image](https://user-images.githubusercontent.com/685880/66139956-f7eb5500-e609-11e9-8128-ae51ae78aac2.png)

As I'm investigating the issue we will either remove they fake key from there or fix it some other way.

**Comment by soulseekah** [comment]
Could not reproduce using shortcode and oEmbeds.

I think we fixed it somewhere between 2.0 and 2.1 I think.

@jlgrisham @rafaehlers can you please run a quick reproduce test so we can close this. Thank you.

**Comment by rafaehlers** [comment]
That was definitely fixed a while ago.
