### ISSUE TITLE
Same-day search range not fetching correct results

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1056]
> Something seems to be strange now. We were on the 1.x series, and a view with an entry date filter, when set to search from 5/10 to 5/10, was pulling back one entry at 1:49am on 5/11. The use timezone filter is not set to false, and the time zone in WP is set correctly to America/Chicago. I checked the logs, and the expected time is being sent to GF.
> 
> This persisted after I upgraded to the GV 2.x series. I dug through the search code, trying variants of what's there, but had no luck. Any insights would be appreciated - the client needs to pull some reports and uses GV exports to do so.

See [HS#14816](https://secure.helpscout.net/conversation/585982839/14816?folderId=408730).

**Comment by rafaehlers** [comment]
I remember @soulseekah fixed that for me a while ago, it was related to the time specified in search query.

**Comment by soulseekah** [comment]
You mean this one 753241530fa446ca09e8387e297e900d9fac06ac @rafaehlers

**Comment by zackkatz** [comment]
Thought: We could try replacing "strtotime" functions here with this replacement
​
```
before: 
[ ... ] strtotime( $variable_name ) [ ... ]

after:
[ ... ] strtotime( $variable_name, current_time( 'timestamp' ) ) [ ... ]
```

**Comment by soulseekah** [comment]
Do you what the difference between `current_time( 'timestamp' )` and `time()` is off the bat? I'll have to look, but I think they're the same, and the default 2nd argument for `strtotime` is `time()`, so... same thing?

**Comment by zackkatz** [comment]
We should use this, which is the GF way:

```$local_timestamp = GFCommon::get_local_timestamp();
$date = strtotime( $filter['value'], $local_timestamp );```

**Comment by soulseekah** [comment]
This seems to occur on both 2.x and 1.x, right?

**Comment by zackkatz** [comment]
Haven’t tested it.

**Comment by soulseekah** [comment]
It's all pretty weird seeing how we even have tests for this, including a GMT offset to +5 hours and +0 hours in https://github.com/gravityview/GravityView/commit/753241530fa446ca09e8387e297e900d9fac06ac

Would be interesting to actually get to play around with this site instead, he says there's sensitive information on there, maybe we can get an NDA going or something, or have him tell us how to reproduce? Cause so far it's working correctly for all of my manual tests, so we must be missing something. There are even tests in GF itself (see `test_search_criteria_date_range_with_utc_offset` for example, which are very similar to ours).

As for local timestamps - WordPress is bad at those. `get_local_timestamp` sort of modifies the timestamp (which is apriori in the UTC zone), this is a bad idea. Doing this several times will certainly offset the date by too much.

Also not sure what current_time and calling `get_local_timestamp` without a timestamp (i.e. just with `time()`) has to do with date ranges in the past.

For a 5/10 to 5/10 setting we have to grab all entries that have been created between midnight 5/10 in the current set timezone and midnight 5/11 in the current timezone.

This is a filter by the `date_created` column, which has no timezone information associated with it. So which timezone is it in? In UTC as per GF:

![image](https://user-images.githubusercontent.com/685880/40627839-bbdddd48-62da-11e8-9378-53e2e1312a59.png)

However, this is what I'm looking at in their search criteria API:

![image](https://user-images.githubusercontent.com/685880/40627898-07d362ea-62db-11e8-8c7b-fa9c5fdfb026.png)

And their code does convert to the needed offset already:

![image](https://user-images.githubusercontent.com/685880/40627991-ac894fac-62db-11e8-82ff-1868bc24bb8d.png)

However, not how `new DateTime` is being used. And here's what the docs say:

![image](https://user-images.githubusercontent.com/685880/40628026-ebd00ec6-62db-11e8-9cf2-91ee3bfeaabc.png)

So let's say that the given date is parsed as a UTC (i.e. the current PHP timezone settings are equal to UTC+0). It's further fed into `get_gmt_from_date`, and you know what that does?

![image](https://user-images.githubusercontent.com/685880/40628062-2f6e8f5e-62dc-11e8-8241-2782bc20dd87.png)

So what we seem to be getting is a UTC date that gets further subtracted. So it end up NOT being UTC.

Let's say that the PHP timezone setting is equal to UTC-5. The date is parsed as UTC-5 converted, further converted by `get_gmt_from_date` back into UTC (I think, it's a bit confusing).

I'm pretty sure that the php.ini timezone setting is actually at play here, offsetting by a bit too much into one of the directions, I think this is a GF bug, GV should only be converting to UTC from the picked dates and feeding GF UTC, exactly what we're doing by calling `get_gmt_from_date`. For systems (PHP) running in the UTC zone this is fine, since they undo our offset by calling `get_gmt_from_date`. But if PHP is running in a different timezone we're probably looking at some extra offset.

I'm continuing to experiment further.

**Comment by soulseekah** [comment]
Tests on the legacy codebase seems to follow perfect logic.

![image](https://user-images.githubusercontent.com/685880/40628535-07d5d454-62df-11e8-8fb8-061524e81952.png)

(As a sidenote, GFQuery behavior changed a bit, if either start date or end date are not set they are set tot the current time).

**Comment by soulseekah** [comment]
Things break badly here, though:

![image](https://user-images.githubusercontent.com/685880/40628978-bfdf6130-62e1-11e8-885e-4f0a2938ad13.png)

This would give us a whole 23 hours 59 minutes 59 seconds of extra range into the next day! Our tests must be incomplete if we're not catching this.

**Comment by soulseekah** [comment]
Isolated case:

![image](https://user-images.githubusercontent.com/685880/40629124-c654b730-62e2-11e8-856f-51c1f2e1c9ec.png)

Why the heck? Checking `GFQuery` now...

![image](https://user-images.githubusercontent.com/685880/40629167-e7ade8e8-62e2-11e8-807e-d9439dc0e836.png)

Duh... why?... ...how... I don't even...

> 00:00:00 is ignored

We got caught in a special case trap, folks. So setting to 00:00:00 is actually bad, a non-working edge case.

Fixes that we can implement:

1. Don't forward by one day, instead set it to 23:59:59 on the same day.
2. Send in 00:00:01 on the next day.

I think option 1 is the better way to go (if there's no other edge case).

And also we need to have a deeper test that actually fetches entries. Relying on verifying the search criteria was a test too shallow, ugh.

Case solved though, I think. The person had an entry pop up where none should have, right?
