### ISSUE TITLE
Single Entry page is unaccessible when Category is used on Post URL Path

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1167]
Assuming your Permalinks is set up this way:

![gv-custom-structure](https://user-images.githubusercontent.com/1222472/46798711-18e7d580-cd29-11e8-85e0-00e2a5c395cf.jpg)

And you embed your Post in a View with this URL path: http://gravityview.com.br/test-category/view-on-a-post/ 

where /test-category/ is the category slug, the single entry page is not accessible: http://gravityview.com.br/test-category/view-on-a-post/entry/11854/

It simply redirects back to the Multiple Entries page: http://gravityview.com.br/test-category/view-on-a-post/

Tested on GV 2.1.0.3

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/682046345/17096/

**Comment by soulseekah** [comment]
> you embed your Post in a View

I guess this is the other way around, a View in a Post, yes?

**Comment by soulseekah** [comment]
The problem is that the rewrite rule that is matched is:

`.?.+?/([^/]+)/entry(/(.*))?/?$ -> `index.php?attachment=$matches[1]&entry=$matches[3]`

While the `(.+?)/([^/]+)/entry(/(.*))?/?$>>index.php?category_name=$matches[1]&name=$matches[2]&entry=$matches[4] post` rule is lower in the list and doesn't get matched.

One way would be to make sure that our entry rules come higher up, although this might have impact on something else. Will take some more time to experiment.

**Comment by soulseekah** [comment]
The roots of the problem go back to 72e40ea4b6c1f1ba14ab1a9223a97fe87b0a2e1e back then I did try to make the registration less pollutant. The time has come.

Fixed, but needs testing in deployments worldwide. Who knows what other rewrite rule collisions there may be.
