### ISSUE TITLE
ACF adds a text box to the bottom of the Edit View screen

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1169]
When ACF Pro (and probably ACF) is enabled, a rich text box gets added to the bottom of the Edit View screen.

**Active plugins:**

GravityView 2.1.0.3
Advanced Custom Fields PRO 5.7.7

**Comment by zackkatz** [comment]
[HS#17259](https://secure.helpscout.net/conversation/689943124/17259)

**Comment by soulseekah** [comment]
Reproduced on my local install.

![image](https://user-images.githubusercontent.com/685880/47618501-e853ba00-dae4-11e8-9453-8cc8942c62ee.png)

**Comment by soulseekah** [comment]
The issue is in `GravityView_Admin_No_Conflict::no_conflict_styles`, the style that is supposed to hide the box (it gets rendered on all types), is getting stripped out here: https://github.com/gravityview/GravityView/blob/master/includes/admin/class-gravityview-admin-no-conflict.php#L134-L152

Going to add ACF.

**Comment by soulseekah** [comment]
The hotfix would be to include this in functions.php:

```php
add_filter(' gravityview_noconflict_styles', function( $styles ) {
    $styles[] = 'acf-global';
    return $styles;
} );
