### ISSUE TITLE
[gvlogic if="{user:ID}" isnot=""] is not working anymore 

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1250]
We suggest this to determine if a user is logged-in or not, but the return is always true.

```
[gvlogic if="{user:ID}" isnot=""]
    Logged
[else]
    Not logged
[/gvlogic]
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995534427851742)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/751586447/18521

**Comment by soulseekah** [comment]
We have unit tests for this and they're not failing.

![image](https://user-images.githubusercontent.com/685880/51072786-c398c880-1677-11e9-8ee3-d707b8cafd7d.png)

Where did you test this?

**Comment by soulseekah** [comment]
Reproduced.

`{user:ID}` is not being converted by Gravity Forms for some reason.

**Comment by soulseekah** [comment]
Okay so,

"anymore" is not the right word here. It never worked outside of Custom Content fields.

Content is not "unmergetagized" inside post content, so it never got converted. It will work in Custom Content because we force the `replace_variables_prepopulate` call ourselves. It's never ran on Post and Page content rendering.

In fact as per above, our tests force the call as well. Without them, `do_shortcode` does absolutely nothing. We need to render the merge tags additionally. I don't think we were ever supposed to use the logic shortcode in post content outside of a view context. That's not the way to use it.

In fact Rafael suggested using some generic content restriction plugins inside post content.

Thoughts @zackkatz?

**Comment by rafaehlers** [comment]
Fixed with the newest logged_id attribute.
