### ISSUE TITLE
Fatal Error and Notices when trying to use a custom table template

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1265]
When I moved those 3 files (table-body.php, table-header.php, and table-footer.php) to a /gravityview/ folder inside my current theme these messages showed up:

```
Notice: Undefined variable: gravityview in C:\MAMP\htdocs\gravity\wp-content\themes\twentytwelve\gravityview\table-header.php on line 12

Notice: Undefined variable: gravityview in C:\MAMP\htdocs\gravity\wp-content\themes\twentytwelve\gravityview\table-header.php on line 14

Notice: Trying to get property of non-object in C:\MAMP\htdocs\gravity\wp-content\themes\twentytwelve\gravityview\table-header.php on line 14

Fatal error: Uncaught Error: Call to a member function the_columns() on null in C:\MAMP\htdocs\gravity\wp-content\themes\twentytwelve\gravityview\table-header.php:14 Stack trace: #0  C:\MAMP\htdocs\gravity\wp-content\plugins\gravityview\includes\class-template.php(963): include() #1  C:\MAMP\htdocs\gravity\wp-content\plugins\gravityview\future\includes\class-gv-template-legacy-override.php(222): GravityView_View->_include('C:\\MAMP\\htdocs\\...') #2  C:\MAMP\htdocs\gravity\wp-content\plugins\gravityview\future\includes\class-gv-renderer-view.php(89): GV\Legacy_Override_Template->render('table') #3  C:\MAMP\htdocs\gravity\wp-content\plugins\gravityview\future\includes\class-gv-view.php(376): GV\View_Renderer->render(Object(GV\View), Object(GV\Frontend_Request)) #4  C:\MAMP\htdocs\gravity\wp-includes\class-wp-hook.php(286): GV\View::content('') #5  C:\MAMP\htdocs\gravity\wp-includes\plugin.php(203): WP_Hook->apply_filters('', Array) #6  C:\MAMP\htdocs\gravity\wp-includes\post-template.php(240): apply_filters('the_content', '') #7  in C:\MAMP\htdocs\gravity\wp-content\themes\twentytwelve\gravityview\table-header.php on line 14
```

Tested with GV 2.2.4

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995532870583490)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/751444518/18518/

**Comment by soulseekah** [comment]
Where did you move them from? Did you just copy them from templates? The names imply that these are legacy templates and may not really work anymore since 2.0. Any clarifications?

**Comment by rafaehlers** [comment]
@soulseekah copied them from the /wp-content/plugins/gravityview/templates/ folder.

**Comment by soulseekah** [comment]
Okay. So I just tested some things:

Copying /templates/deprecated/table-body.php to /gravityview/table-body.php works well i.e. the legacy renderer kicks in as it's supposed to. No warnings as far as I can tell. There's certainly no function call to `the_columns`.

Copying /templates/view/table/table-body.php to /gravityview/table-body.php will result in an error, but that's because it's the wrong context, directory. You should not place 2.0 template overrides files into /gravityview/ directly. Our documentation should state this clearly:

/templates/views/table/table-body.php should go to /gravityview/views/table/table-body.php i.e. the subdirectory structure should be respected. No warnings or errors will occur.

That said, we should probably make sure the 2.0 templates do not fatal out merely by misplacing them like this, an easy mistake to make. I'll think of some protection that we can have. Otherwise please advise the client on the correct place to put the template in their theme, @rafaehlers 

Thanks.

**Comment by soulseekah** [comment]
I've pushed a commit with an error message to the debug log. The template will not load at all to prevent a fatal error. The message may need some fine tuning perhaps if anyone complains that it's not clear enough or something. Otherwise closing.

**Comment by soulseekah** [comment]
Oops, I meant this can be closed with the next release.

**Comment by rafaehlers** [comment]
I updated the docs with the new instructions: https://docs.gravityview.co/article/64-overriding-gravityview-templates
