### ISSUE TITLE
The new approval field scrolls back to top after being clicked

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1312]
Here's a video showing the behavior: https://monosnap.com/file/MIfqHf7iTbyMk9zyBN8G5wqUyChvT0

Tested on GV 2.3.1

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1121098071682814)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/843487678/20504

**Comment by verysiberian** [comment]
Hello! I realize that I may be an edge case here, but this issue is particularly disruptive to the workflow I have planned for an event coming up soon in which multiple volunteers will be clicking to approve GravityView entries as a mechanism for documenting attendance at a conference. Do you expect that this bug will be fixed soon? I ask because I'll probably have to hire someone on Codeable to do it if it's not forthcoming. Of course, I would rather avoid that but I'm the one who is kind of desperate.

**Comment by zackkatz** [comment]
That’s no good! Can you share your browser details? Please copy and paste from here: https://www.whatsmybrowser.org/

@mrcasual let’s make sure this works!

**Comment by verysiberian** [comment]
Thank you!

https://whatsmybrowser.org/b/K4STX2S

**Comment by verysiberian** [comment]
Also, FYI, it happens on Safari (iOS) and in Chrome on Mac, e.g.,

https://whatsmybrowser.org/b/FURXFFM

**Comment by verysiberian** [comment]
If it helps, this bug is not present in GravityView 2.3. I just temporarily reverted to that version until there is a fix.

**Comment by verysiberian** [comment]
Hey, any possible ETA on this one?

**Comment by zackkatz** [comment]
Hey @verysiberian You can use this build, which fixes the issue: https://share.gravityview.co/cM5E9N+

Let me know if it doesn't work for you; it works for me.

**Comment by zackkatz** [comment]
This'll also be included in the next minor update.

**Comment by verysiberian** [comment]
Thank you very much! This solves the problem.
