### ISSUE TITLE
Unapprove Entries After Edit feature is not working

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1368]
![image](https://user-images.githubusercontent.com/1222472/67825730-0ada3380-faa9-11e9-9982-9fa66b54beac.png)

I used an Editor role to edit an existing entry submitted by another user and the entry kept is approval state = Approved.

Tested with GV 2.4.1.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/982401118/22939/

**Comment by soulseekah** [comment]
Very possibly related https://secure.helpscout.net/conversation/987967925/23050?folderId=408733tleg

**Comment by soulseekah** [comment]
Checked with Subscriber role. Entry was unapproved correctly.

**Comment by soulseekah** [comment]
Our autounapprove feature is only called if all of these conditions are met:

1. editing from the frontend (specifically via the gravityview/edit_entry/after_update action)
2. with the feature turned on for a View (check the Settings)
3. only for non-admins (accounts with gravityview_moderate_entries
4. gravityview/approve_entries/autounapprove/status filter is not set anywhere to false

I've tested this and since an Editor has `gravityview_moderate_entries` we are failing on point 3 above. This is expected behavior. Won't fix.

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/1005071625/23359/ also somewhat related but this is not the autounapprove feature as far as I can tell. They're editing from the backend.

**Comment by rafaehlers** [comment]
@zackkatz let's make it work for admin as well (please check point 3 above and @soulseekah 's comment below). It'll be intuitive that way. I didn't know myself that only worked for non-admins.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/982401118/22939

**Comment by soulseekah** [comment]
> Unapprove no matter what on the edit screen:

```php
add_action( 'gravityview/edit_entry/after_update', function( $form, $entry_id ) {
    gform_update_meta( $entry_id, 'is_approved', 3, $form['id'] );
}, 10, 2 );
```

**Comment by zackkatz** [comment]
@jlgrisham Can you please write a doc with Gennady's snippet?

**Comment by soulseekah** [comment]
No doc yet, I'm guessing?

**Comment by zackkatz** [comment]
https://docs.gravityview.co/article/657-unapproving-edited-entries-automatically?auth=true
