### ISSUE TITLE
wp_kses conflicting with < > characters inside paragraph fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1417]
If you add a text like this inside a Paragraph field, the View will crop the text inside the `<` and `>` characters:

`Sed ut perspiciatis unde omnis <iste natus error sit voluptatem accusantium> doloremque`

Output on the View:

`Sed ut perspiciatis unde omnis doloremque`

Because of the line 29 in `wp-content\plugins\gravityview\templates\fields\field-textarea-html.php`

>$value = wp_kses( $value, $allowed_html );

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1085700089/25338/

**Comment by soulseekah** [comment]
It's treating it as a tag. Since the the Textarea field is HTML-aware the content users put in should be valid HTML. In valid HTML `<` is `&lt;` and `>` is `&gt;`.

Adding a setting is probably the best option - "Allow HTML". Having it on would do the wp_kses stuff and expect valid HTML. Having it off would just run esc_html on the output escaping any and all HTML. Best of both worlds.
