### ISSUE TITLE
[gvfield] is not displaying the dropdown label as specified on the View editor

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1597]
![image](https://user-images.githubusercontent.com/1222472/116633748-b4191880-a930-11eb-9b7b-46477b262998.png)

![image](https://user-images.githubusercontent.com/1222472/116633715-a2d00c00-a930-11eb-94b9-3377194732a2.png)

![image](https://user-images.githubusercontent.com/1222472/116633836-e88cd480-a930-11eb-8b97-cf714e34040a.png)

Output is "2"

Tested with GF 2.5 and GV 2.10.2.2

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1497412981/34113/

**Comment by omarkasem** [comment]
- I tried to use the filter 'gravityview/field/select/value' to get 'choice_display' configuration but that did not work and filter the value but that didn't work as the context is different.
- Also tried to update the current field view configuration and add 'choice_display' but can't get that value at all from that context.
- The only solution that worked and it's really simple without changing anything is do just add the 'choice_display' as an attribute to the shortcode like that
`
[gvfield view_id=33 entry_id="first" field_id="2" choice_display='label']
[gvfield view_id=33 entry_id="first" field_id="2" choice_display='value']
`

**Comment by zackkatz** [comment]
@rafaehlers Turns out you can pass field settings overrides into the shortcode and they get handled.

So adding `choice_display='label'` or `choice_display='value'` to the `[gvfield]` shortcode will make it render properly.

I'll add to the doc, but this is resolved.

`[gvfield view_id=855 entry_id="first" field_id="1" choice_display='label']`

![](https://i.gravityview.co/ew1qSx+)
