### ISSUE TITLE
Certain Gravity Forms Conditional Logic rules don't show/hide Update button in edit entry

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#510]
The "Is User Logged In" conditional logic may not trigger the "Update" button properly.

Needs confirmation.

See https://secure.helpscout.net/conversation/118996073/3285/

**Comment by rafaehlers** [comment]
@zackkatz I'm not sure this is a problem. I have been advising users that report the missing Update button to check their conditional logics. We can leave it like that or we can choose to ignore it. Maybe if we ignore it, it'll be better since most of these conditional logics apply only to form submission and not edit entry (an already submitted form).
