### ISSUE TITLE
Add "all" option to "show only" links in the search bar

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#559]
> If I only have a links option in my search bar, the only way to show all entries once a link is clicked is to include a reset button and click that. If only the links are showing though, it would be much tidier and intuitive (in my opinion) to be able to click a show "all" link.

See https://gravityview.uservoice.com/forums/238941-gravityview-ideas/suggestions/9084997-add-all-option-to-show-only-links-in-the-searc

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995627291840115)

**Comment by rafaehlers** [comment]
We still don't have this in GV 2.8.1

**Comment by zackkatz** [comment]
Does it need to be an "all" link? What about an "x" icon next to the active link?

If "all" link is needed, should it appear first, last, or outside the list?

@rafaehlers

**Comment by rafaehlers** [comment]
By putting an "x" icon next to the active link, leads me to think it'll work like tags, and I can click on other links to increment the search. 

The "All" link will work as a Reset, which we already have and in order to display that, we'll need to check if that's the only filter available on the Search Bar. Honestly, this is duplicating functionality. I think we should abandon this idea at all.

**Comment by zackkatz** [comment]
We will be addressing this in a bigger Search Bar rewrite and reconceptualization.
