### ISSUE TITLE
ASC sort not 100% functional

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#569]
![cma-01](https://cloud.githubusercontent.com/assets/1222472/10745987/8d04838c-7c2d-11e5-9664-1e5fa6d73a3a.jpg)

Some records of page 1 are appearing on page 2:

![cma-02](https://cloud.githubusercontent.com/assets/1222472/10745988/8d3f4f8a-7c2d-11e5-879d-d6ca7006c304.jpg)

Related: https://secure.helpscout.net/conversation/132596856/3866/

**Comment by rafaehlers** [comment]
Realted: https://secure.helpscout.net/conversation/150139060/4456/

**Comment by luistinygod** [comment]
When sorting issues appear, it is also important to check on the Gravity Forms entries screen (in the WP admin) to see if they also happen there. If yes, then my experience on trying to fix this issues tell me that the root cause for this problem is on the Database, probably due to some data import. One way to try to fix this is to export all the entries, delete the entries in the installation and import them again.

**Comment by luistinygod** [comment]
Another one https://secure.helpscout.net/conversation/164761308/4760/

**Comment by luistinygod** [comment]
We need help from Gravity Forms team..

**Comment by luistinygod** [comment]
Release 1.9.16 of Gravity Forms might fix this issue:
> Fixed issue with entry list sorting on certain mySQL installations.
https://www.gravityhelp.com/gravity-forms-v1-9-16-released/
