### ISSUE TITLE
Calculation isn't triggered when updating entry

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#626]
1) Create a form with 2 single line text inputs: Field 1 and Field 2
2) Add a third field Number and enable calculation for this field: {Field one:1} + {Field two:2}
3) Add one entry = works
4) Create a View, edit one of these two single line text fields
5) Calculation doesn't work.

![gv-calculation](https://cloud.githubusercontent.com/assets/1222472/12935548/aac9d680-cf7d-11e5-889f-58c79d0e2549.jpg)

Tested on:
GravityView - Version 1.16.1 
Gravity Forms - Version 1.9.16

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/160628675/4643/

**Comment by luistinygod** [comment]
This happens when the calculation field is not part of the editable fields in the view. The quick workaround is to add the calculation field to the Edit Entry tab configuration and assign a class "hidden" so it won't appear on the frontend. 
![screen shot 2016-02-10 at 15 13 55](https://cloud.githubusercontent.com/assets/2511389/12951186/0243e564-d009-11e5-9280-0628b4c3e7e6.png)

**Comment by luistinygod** [comment]
Meanwhile this will be fixed in the core.
