### ISSUE TITLE
Support Gravity Forms Repeater Add-On on the Edit Entry page

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#761]
The error message on the Edit Entry page:
Uncaught SyntaxError: Unexpected token a in JSON at position 0

the returned JSON:

a:2:{i:1;a:1:{i:6;a:1:{i:0;s:21:"http://gravityview.co";}}i:2;a:1:{i:6;a:1:{i:0;s:28:"https://demo.gravityview.co/";}}}

Related:
- https://wordpress.org/plugins/repeater-add-on-for-gravity-forms/
- https://secure.helpscout.net/conversation/250236893/6897/?folderId=408730

**Comment by zackkatz** [comment]
Should be addressed with a `GravityView_Plugin_and_Theme_Hooks` sub-class.

**Comment by pinksharpii** [comment]
What is the status of this? I don't see a GravityView_Plugin_and_Theme_Hooks subclass created for this plugin. I too am having this issue. A little more explanation on how the class needs to be setup and what the function needs to do to prevent this error would be helpful.

**Comment by soulseekah** [comment]
The Repeater Add-On has been abandoned and is currently not being maintained. It currently has over 30 submitted issues on GitHub.

Here are some related issues I could find:

- https://github.com/kodie/gravityforms-repeater/issues/81 (fields not editable in Gravity Form Entry Edit in the backend)
- https://github.com/kodie/gravityforms-repeater/issues/67 (fields cannot be prepopulated, directly related to this issues)
- https://github.com/kodie/gravityforms-repeater/issues/54 (can't edit fields via the admin)
- https://github.com/kodie/gravityforms-repeater/issues/43 (entries not editable from admin)

This is definitely a bug on the plugin side and not an incompatibility with GravityView. GravityView uses the Gravity Forms APIs to render the edit form and the Repeater Add-On simply doesn't work with Gravity Forms at this point.

So, ideally, this has to be fixed upstream. Putting a flaky hack together in the form of a "compatibility" layer is probably pointless if possible at all.

**Comment by soulseekah** [comment]
A quick update after some time with the add-on - there's absolutely no functionality that hints at editing in there. The closest thing that it does support is the `prePopulate` setting when rendering, but that would conflict with the actual pre-populate setting when creating these fields. And even then, the prePopulate field doesn't support added instances of a repeat, there's no code to create them.

Overall, I'm sure we could override the whole rendering routines and write all the editing logic in GravityView for this plugin (including stubbing out the shipped JavaScript logic, because it contains nothing that supports editing either), but that sounds like a step in a very wrong direction and will take a couple of days of full-time work. Work that should actually be done on the upstream repository (i.e. the Repeater Add-On code). Even better, work that should be done on Gravity Forms to provide core repeating functionality :smile:

Any thoughts, ideas are always appreciated, so keep them coming :+1:

**Comment by zackkatz** [comment]
Yeah, Gravity Forms is working on this for core. Not sure when it will be released, but I don't think we should support the Repeater addon. Instead we will support core functionality.

**Comment by pinksharpii** [comment]
That makes sense. I didn't realize how problematic it was. It's about time it becomes a core feature! I've found a sort of workaround for now, hooking into `gravityview/edit-entry/render/before`

**Comment by floatytheastronaut** [comment]
FreeScout #77543. <br>https://support.gravitykit.com/conversation/77543?folder_id=1
