### ISSUE TITLE
Add filter to allow support for rewrite > with_front argument on our Custom Post Type

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#782]
From a customer:

> We use /blog/ in our custom permalink structure. As a result, /blog/is prepended to any GravityView permalinks. Is it possible to add 'with_front' => false via hook in our functions.php file to remove /blog/ from all GravityView permalinks?

Checking on includes/class-post-types.php function `init_post_types` at line 34, there's no filter available to support that argument, only a filter for `rewrite > slug`:

![gv-rewrite-filter](https://cloud.githubusercontent.com/assets/1222472/19485885/2c485b9a-953b-11e6-83a6-946043203e14.jpg)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/265243188/7210/?folderId=408730

**Comment by soulseekah** [comment]
This is ready to be implemented in the future branch and hit master in a matter of weeks I think, since we've already moved the registration code we can afford to add this change.

Filter `gravityview/post_type/with_front`.

Will be `true` by default, matching the WordPress default. Although it should have probably been `false` from the beginning of time, but obviously we can't change this now due to regressions.

**Comment by soulseekah** [comment]
For older versions (that have none of the `future` code we're deploying) people can hack that argument via the core `register_post_type_args` filter seen here https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/class-wp-post-type.php#L357
