### ISSUE TITLE
Adding a DataTable after a Table View or List View breaks sorting links

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#817]
GV 1.19.2

![gv-data-table](https://cloud.githubusercontent.com/assets/1222472/21462777/126c64d8-c947-11e6-926d-c86e742e2a35.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995651965441261)

**Comment by soulseekah** [comment]
Needs a retest, but I'm like 100% sure that this would happen with sorts on two different Views on the same page.

The same would happen with search.

Why? Simply because the URL scheme does not support binding search and sort parameters to a View. I was thinking about this lately, we should have a new scheme that supports this.

Related to https://github.com/gravityview/GravityView/issues/1200

Developing a new JSON-based sort and filter parameters would probably help.

`sort={"VIEWID": {"1":"desc","34":"asc"}, "VIEWID": {"4":"desc"}}&filter={"VIEWID":{"4":{"op":"is","value":"hello"}}`, etc

**Comment by rafaehlers** [comment]
I can't seem to replicate this as of GV 2.13.1:

![image](https://user-images.githubusercontent.com/1222472/135929081-4fb62d2f-141f-42e3-bc3e-94ca09ab77e3.png)
