### ISSUE TITLE
After edit/delete an entry keep the search results

### ISSUE THREAD

**Issue by daizprua** [gravityview/GravityView#830]
I made a search on my reults, now I need keep the search results, but when delete some entry get back to all results and I need to search again. How can I resolve that?

Screenshot: http://prntscr.com/dzfuex

Thansk for the help

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995652727397778)

**Comment by zackkatz** [comment]
Hi @daizprua - there is no current way to do this. Thanks for opening the issue.

**Comment by daizprua** [comment]
Thanks zackkatz

**Comment by zackkatz** [comment]
It would happen here: https://github.com/gravityview/GravityView/blob/2.0/includes/class-api.php#L619-L631

**Comment by soulseekah** [comment]
Can someone retest this, please with current `develop`?

**Comment by rafaehlers** [comment]
I believe this can be solved with this: https://github.com/gravityview/GravityView/issues/1468

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1319279152/29934/

**Comment by shamalisulakhe** [comment]
To redirect to multiple entries page with search parameters applied, a possible approach is - 

If the redirect link is added to the URL of single entry like - 
http://_site_url_/view/test-form-view/entry/123/?redirect_link=_site_url_/view/test-form-view/?gv_search=teststring&mode=any

This will take the redirect link from the URL and will redirect to - 
_site_url_/view/test-form-view/?gv_search=teststring&mode=any

To shorten it futher, only search parameters can be appended to URL instead of entire redirect link.

**Comment by zackkatz** [comment]
This has been implemented with #1561
