### ISSUE TITLE
Offset attribute may not be functional in [gravityview] shortcode

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#851]
We need to create some tests to make sure that the `offset` works properly.

- `[gravityview id="123" offset="0"]` or `[gravityview id="123" offset=""]` Should start at 1st entry
- `[gravityview id="123" offset="5"]` Should start at 6th entry
- `[gravityview id="123" offset="100"]` Should start at 101st entry

While we're at it, we should make `page_size` tests as well.

https://secure.helpscout.net/conversation/309918705/

**Comment by soulseekah** [comment]
Tests fail: https://travis-ci.org/gravityview/GravityView/builds/206092292

Tests pass: https://travis-ci.org/gravityview/GravityView/builds/206093915

Manual visual testing seems to work, too. Although, I don't see any pagination links when setting the `page_size` to something smaller than the amount of entries I have.

`page_size="5"`

![image](https://cloud.githubusercontent.com/assets/685880/23397318/d24175e0-fdb9-11e6-9f8f-d63db3465f3b.png)

`page_size="1"`

![image](https://cloud.githubusercontent.com/assets/685880/23397334/dc5621e8-fdb9-11e6-88b2-f6d3c920c40b.png)

No pagination. Could be either a misconfiguration on my end or a bug.

**Comment by soulseekah** [comment]
Nvm, it's was a misconfiguration on my end. The Paging widget got removed.

But of course there has to be a bug in pagination as well, which gets exposed by fixing something!

![image](https://cloud.githubusercontent.com/assets/685880/23400237/22e4c1e0-fdc5-11e6-9bcd-8728a619c5ed.png)

See, if offset is set (and by default it's set to 0 now, which exposed this bug), pagination is ignored completely!

Tests and fix incoming.

**Comment by soulseekah** [comment]
And of course the totals are broken, as well, resulting in the total number of pages to be skewed beyond the offset with trailing pages containing empty entries.

This happens because `GFAPI::count_entries` disregards all offsets, used in `GravityView_frontend::get_entries`, so need to subtract the offset there.

So `GravityView_View::getPaginationCounts` is completely off on all counts. It gets the wrong total, it doesn't appear to be doing the offset calculations correctly, either.

Will look more later.
