### ISSUE TITLE
File Upload not saving properly in 1.20

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#852]
> There is an issue with Upload File fields:
> 
> 1. When you show an entry with Gravity View, the uploaded file is available (clickable).
> 
> 2. But after you update any field of the entry with Gravity View, the uploaded file is no longer available (not clickable, just a red x with the file url).

See https://secure.helpscout.net/conversation/149284311/4437

**Comment by rafaehlers** [comment]
Also related: https://secure.helpscout.net/conversation/322770733/8326/?folderId=408735

**Comment by zackkatz** [comment]
And https://secure.helpscout.net/conversation/325782321/8404/?folderId=408730

**Comment by soulseekah** [comment]
For documentation purposes:

In 27748a5 the edit links stopped getting the 'view=entry' parameter. Turns out it's still needed for fileupload fields to work correctly:

![image](https://cloud.githubusercontent.com/assets/685880/23469864/b3b965f2-fec6-11e6-9c84-22744f4c3175.png)

There's a short circuit in `FormsModel::save_input` that kicks off for fileupload fields, which if not taken will try to overwrite the upload on save. One of the checks depends on `$_GET['view']` being set to `"entry"` (early on via the `RG_CURRENT_VIEW` constant definition).

The quick fix would be to return that parameter to the edit links.

The long-term fix would require us to recode the whole saving routines ourselves (perhaps by consuming the GF REST API?)

Thoughts?

**Comment by soulseekah** [comment]
Fix in 346836529b926aa439496ae4e970e52934ba88d8

You can probably start a PR.

**Comment by soulseekah** [comment]
Stab at a fix here https://github.com/gravityview/GravityView/commit/28ce211d5cb99f542a147a2348da165eb248732a

**Comment by zackkatz** [comment]
28ce211 fixed the issue for all customers who responded.
