### ISSUE TITLE
Possible PATH issues on IIS servers

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#895]
`An error occurred while updating GravityView: Could not create directory. gravityview/includes/extensions/delete-entry/fields`

The user has said:
>permissions are set correctly. No other plug-ins have issues and this only occurs on that same file each time. Servers are running IIS 7.5/8 or 8.5.
>I feel like the issue may be that the path is not completely specified?
>
>gravityview/includes/extensions/delete-entry/fields
>
>This path would try to create a directory one level below where the program was running from

Related: https://secure.helpscout.net/conversation/335671297/8584/?folderId=408735

**Comment by soulseekah** [comment]
This directory is not created by us at all. It's created by the WordPress Plugin_Updater component via the Filesystem API, nothing special about our plugin here.

```
includes/class-wp-upgrader.php:170:             $this->strings['mkdir_failed'] = __('Could not create directory.');
includes/file.php:692:                  return new WP_Error( 'mkdir_failed_ziparchive', __( 'Could not create directory.' ), substr( $_dir, strlen( $to ) ) );
includes/file.php:798:                  return new WP_Error( 'mkdir_failed_pclzip', __( 'Could not create directory.' ), substr( $_dir, strlen( $to ) ) );
includes/file.php:851:                                  return new WP_Error( 'mkdir_failed_copy_dir', __( 'Could not create directory.' ), $to . $filename );
includes/update-core.php:1173:                                  return new WP_Error( 'mkdir_failed__copy_dir', __( 'Could not create directory.' ), $to . $filename )
```

Perhaps the user has configured the upgrade mechanism to FTP (instead of FS_DIRECT) to upgrade, in which case it could be this core issue: https://core.trac.wordpress.org/ticket/26802 (seems like an issue in the internal WordPress FTP client library).

**Comment by zackkatz** [comment]
Let's close and re-open if the customer grants access and we find an issue.
