### ISSUE TITLE
Add support for displaying Views in the Admin

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#923]
This is a common request.

Not sure how this would be implemented—maybe generate an "Admin View" link that displays Views on an admin screen?

https://secure.helpscout.net/conversation/431218100/10959/?folderId=408735

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656581125577)

**Comment by zackkatz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Display Views in the Admin](https://trello.com/c/NPelUiTo/98-display-views-in-the-admin)

**Comment by soulseekah** [comment]
In an iframe?

**Comment by zackkatz** [comment]
> In an iframe?

I don't like that idea much…maybe just because of IFRAMEs and the "old days of the interwebs." I'd much prefer to have it work natively.

**Comment by soulseekah** [comment]
Well, off the top of my head, Stripe and Google use iframes, so does WordPress (Theme Customizer), I believe. So there's no old days stigma for sure. But I think we can make it work without, sure.

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/66326849-6bef6b00-e932-11e9-9218-3718dd5a3c9b.png)

I'll start by doing something like this as an experiment and see where it takes us in terms of rendering in the admin (#1153, #946)

**Comment by soulseekah** [comment]
Meh, I still think that doing this the `iframe` way is the way to go here. All of our rendering is protected by `is_admin` calls because core is not loaded in the backend.

The closest I come is via a Mock Request-faked render:

![image](https://user-images.githubusercontent.com/685880/66330246-a825ca00-e938-11e9-8411-5980bc42c15b.png)

We do this in our tests. We can theoretically bootstrap off of this and provide a wrapper for people to use or a plugin for this. Will give it a couple of more thoughts, attempts and punt this to Low priority until someone else requires this.

**Comment by soulseekah** [comment]
[adminview.zip](https://github.com/gravityview/GravityView/files/3698537/adminview.zip) is a test plugin with a very very rough idea. Moving to low priority and hard difficulty :dango:

**Comment by zackkatz** [comment]
Okay, closing this for now.

**Comment by soulseekah** [comment]
Why reopened? :) We have a new repo now don't we? :) https://github.com/gravityview/Admin-Views/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1358309617/31163
