### ISSUE TITLE
Notice: Undefined offset class-edit-entry-render.php on line 460

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#977]
When WP_DEBUG is true, we get that when editing an entry:

>Notice: Undefined offset: 13 in /home3/grcranet/public_html/aahs63_prod/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-render.php on line 460

Line 460 is the return:

```
/** No file is being uploaded. */
if ( empty( $_FILES[ $input_name ]['name'] ) ) {
 /** So return the original upload */
 return $entry[ $input_id ];
}
```

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/534470565/13622/

**Comment by soulseekah** [comment]
Requested more information from initial reporter. We've not seen anything like this, would be nice to reproduce.

**Comment by zackkatz** [comment]
Silencing the warning is simple; just don't assume the key exists.

```
return rgar( $entry, $input_id, '' );
```

This would fix the PHP warning, but maybe it shouldn't be silenced without understanding the bug…when we have another report, let's look into it more.

I imagine this is what is happening: when deleting a file so that no files exist for the field, the `$_POST` and `$_FILES` are empty for that key. The `$entry` value may already be `unset()` or otherwise no longer existing. Asking for that value no longer makes sense. 

The question is, for an *actual fix*: should we return `$value` instead of an empty string? That requires testing, which I haven't done.
