### ISSUE TITLE
2.0: Re-Implement minimum future version admin notices

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#997]
In 1.x, we have notices warning users if they are using versions of plugins less than the following:

- [x] `GV_FUTURE_MIN_PHP_VERSION`
- [x] `GV_FUTURE_MIN_GF_VERSION`

We should re-implement these notices in 2.0 https://github.com/gravityview/GravityView/commit/90226ef97540c2ed285313717d1ce852bacdf00e

**Comment by soulseekah** [comment]
These notices are being shown since the legacy class is loaded:

![image](https://user-images.githubusercontent.com/685880/39038207-590815e6-449c-11e8-9759-4d03582d6434.png)

Have you encountered issues where it hasn't, or has the time approached to refactor this class and keep it for back-compat only?

**Comment by zackkatz** [comment]
Yeah, it's not loading. Try updating to:

```
define( 'GV_FUTURE_MIN_PHP_VERSION', '15.4' );
```

It won't trigger the notification.

`$future_min_php_version` and `$future_min_gf_version` both aren't used. Patch coming.

**Comment by soulseekah** [comment]
Hmm, the soon text disappeared somewhere between `develop` and `2.0`, not sure why, probably a mistake.
